#:import MapView kivy.garden.mapview.MapView

MapView:
    lat: 10
    lon: 10
    zoom: 5
    double_tap_zoom: True
    on_lat:
        print('lat',self.lat)
    on_lon:
        print('lon', self.lon)
    MapMarkerPopup:
        source: "marcador.png"
        lat: 11
        lon: 11
        Button:
            on_release: 
                root.center_on(14,14)
                print(root.get_bbox())
            
            